project_id = "brand_your_mac"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 17

[db.migrations]
enabled = true
schema_paths = []

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[realtime]
enabled = false

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[inbucket]
enabled = false

[storage]
enabled = true
file_size_limit = "2MiB"

[auth]
enabled = true
site_url = "https://brand-anything.vercel.app"
additional_redirect_urls = ["https://brand-anything.vercel.app", "https://brand-anything.vercel.app/sell", "https://brand-anything.vercel.app/auth/callback", "https://brand-anything.vercel.app/auth/reset-password"]
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
secure_password_change = false
max_frequency = "5m"
otp_length = 8
otp_expiry = 3600

[edge_runtime]
enabled = false

[analytics]
enabled = false
